Algoritmo "Area do Quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
var
area:real
lado1:real


Inicio
escreval("Digite o lado do quadrado:")
leia(lado1)

area <- lado1 * lado1

escreval("A área do quadrado, com a altura = ",lado1," vezes a base = ",lado1," é: ",area)

Fimalgoritmo