Algoritmo "Área do Círculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
var
area:real
raio:real

Inicio
escreval("Digite o raio do cículo:")
leia(raio)

area <- 3.14 * (raio * raio)

escreval("A área do círculo, com o raio = ",raio,", é: ",area)

Fimalgoritmo